apiVersion: v1
kind: Pod
metadata:
  name: swagger
  labels:
    app: swagger-openshift
    owner: sbraman
    vendor: stp
spec:
  restartPolicy: Always
  containers:
  - name: swagger
    image: quay.io/sbraman/swagger-openshift:v1
    imagePullPolicy: Always
    resources:
      requests:
        memory: "100Mi"
        cpu: "200m"
      limits:
        memory: "200Mi"
        cpu: "300m"
    env:
    - name: BASE_URL
      value: "/swagger" 
    - name: SWAGGER_JSON
      value: "/ocp-4-11-0.json"
    ports:
    - containerPort: 8080
