apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: qualys-cloud-agent
  namespace: qualys-agent
  labels:
    k8s-app: qualys-cloud-agent
spec:
  selector:
    matchLabels:
      name: qualys-cloud-agent
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: qualys-cloud-agent
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccount: qualys-agent-sa
      containers:
        - name: qualys-cloud-agent-container
          image: qualys/linux-cloud-agent:3.5.0-20
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "0.2"
          args:
            [
              "--activation-id", "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
              "--customer-id", "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
              "--provider-name", "<provider name>",
              "--log-level", "<optional log level>",
              "--server-uri", "https://qagpublic.qg1.apps.qualys.com/CloudAgent"
            ]
          volumeMounts:
            - mountPath: /host_root
              name: root-host-path
            - mountPath: /usr/local/qualys/cloud-agent/data
              name: data-host-path
            - mountPath: /etc/qualys/cloud-agent
              name: config-host-path
            - mountPath: /var/log/qualys
              name: log-host-path
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
      volumes:
        - hostPath:
            path: /
            type: Directory
          name: root-host-path
        - hostPath:
            path: /usr/local/qualys/cloud-agent/data
            type: DirectoryOrCreate
          name: data-host-path
        - hostPath:
            path: /etc/qualys/cloud-agent
            type: DirectoryOrCreate
          name: config-host-path
        - hostPath:
            path: /var/log/qualys
            type: DirectoryOrCreate
          name: log-host-path
