kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qualys-agent-rolebinding
  namespace: qualys-agent
subjects:
  - kind: ServiceAccount
    name: qualys-agent-sa
    namespace: qualys-agent
roleRef:
  kind: Role
  name: qualys-agent-role
  apiGroup: rbac.authorization.k8s.io
