kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: qualys-agent-scc
allowHostDirVolumePlugin: true
allowHostNetwork: true
allowHostIPC: true
allowHostPID: true
allowHostPorts: true
allowPrivilegedContainer: true
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
  - system:serviceaccount:qualys-agent:qualys-agent-sa
