apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: acm-operator-subscription
  annotations:    
    argocd.argoproj.io/sync-wave: "2"
  #finalizers:
  #- resources-finalizer.argocd.argoproj.io 
spec:
  sourceNamespace: openshift-marketplace
  source: redhat-operators
  channel: release-2.8
  installPlanApproval: Automatic
  name: advanced-cluster-management