apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1" 
  #finalizers:
  #- resources-finalizer.argocd.argoproj.io
spec:
  finalizers:
  - kubernetes