apiVersion: v2
appVersion: "1.0.2"
description: A Helm Chart for K8s
icon: https://cdn.icon-icons.com/icons2/2699/PNG/512/openshift_logo_icon_169886.png
name: Logging
type: application
version: 1.4.0
