---
apiVersion: v1
kind: Service
metadata:
  name: grpc-multus01-service
  labels:
    app: grpc
    role: grpc-multus01-service
spec:
  clusterIP: None  
  ports:
  - name: grpc-listen
    protocol: TCP
    port: 50051
    targetPort: 50051
---
apiVersion: v1
kind: Endpoints
metadata:
  name: grpc-multus01-service
subsets:
  - addresses:
      - ip: 192.168.4.13  # <--- grpc-server static pod IP set by NetworkAttachmentDefinition "server-red-network" 
    ports:
      - port: 50051
...
