apiVersion: v1
kind: Service
metadata:
  name: grpc-external-service
  labels:
    app: grpc
    role: grpc-external-service
spec:
  type: NodePort
  selector:
    role: grpc-server
  ports:
  - name: grpc-np
    protocol: TCP
    port: 50051 
    targetPort: 50051
    nodePort: 30007

# Test from external client:
# cd /tmp/grpc-go/examples/helloworld/greeter_client/ && go run main.go && cd /home/sbraman/crc
