apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: server-red-network
  labels:
    app: grpc
    role: server-nad
spec:                                 
  config:
    '{
      "cniVersion": "0.3.1",
      "name": "red-network",
      "type": "macvlan",
      "mode": "bridge",
      "master": "",
      "ipam": {
        "type": "static",
        "addresses": [
         {
          "address": "192.168.4.13/24"
         }          
        ]      
      }
    }'

# static IP for grpc "thick-server" container
