apiVersion: v1
kind: Service
metadata:
  name: grpc-internal-service  
  labels:
    app: grpc
    role: grpc-internal-service
spec:
  type: ClusterIP
  selector:
    role: grpc-server
  ports:
  - name: grpc-listen
    protocol: TCP
    port: 30007
    targetPort: 50051
