apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: grpc
    role: grpc-lb-service
  # annotation options for bigIP F5 CIS
  #annotations:
    #cis.f5.com/ip: 10.25.84.200
    #cis.f5.com/ipamLabel: test
spec:
  type: LoadBalancer
  #loadBalancerIP: 192.168.130.20  # <--- For metalLB, specify IP from pool range to use (optional)
  selector:
    role: grpc-server
  ports:
  - name: grpc-listen
    protocol: TCP
    port: 30010 # port exposed on the loadbalancer
    targetPort: 50051 # port grpc server container is listening on
    nodePort: 30030 # port opened / allocated on the nodes. Remove if below is set to false
  allocateLoadBalancerNodePorts: true 
  # some cloud LBs and F5 support this being set to false. In this case, traffic flows from
  # the external LB to the target pod IPs directly and thus nodePort and Kube-Proxy 
  # are not required