apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: client-red-network  
  labels:
    app: grpc
    role: client-nad
spec:                                 
  config:
    '{
       "cniVersion": "0.3.1",
       "name:": "red-network",
       "type": "macvlan",
       "mode": "bridge",
       "master": "",
       "ipam": 
         {          
           "type": "whereabouts",       
           "range": "192.168.4.0/24", 
           "range_start": "192.168.4.2", 
           "range_end": "192.168.4.10"           
         }
    }'    

# dynamic IP using wherabouts ipam plugin    
