apiVersion: v1
kind: Pod
metadata:
  name: apache
  labels:
    app: apache-openshift
    owner: sbraman
spec:
  restartPolicy: Always
  containers:
  - name: acache
    image: quay.io/sbraman/apache:v1
    imagePullPolicy: Always
    resources:
      requests:
        memory: "100Mi"
        cpu: "200m"
      limits:
        memory: "200Mi"
        cpu: "300m"
    ports:
    - containerPort: 8080
