---
apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management
  labels:
    argocd.argoproj.io/managed-by: ocp-gitops
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:  
  name: acm
  namespace: ocp-gitops
  #namespace: openshift-gitops
  labels:
    appgrp: day2
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: open-cluster-management
    server: https://kubernetes.default.svc
  project: default
  source:
    #directory:
      #recurse: true
    path: src/acm
    repoURL: https://github.com/gsbraman/stp
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    #syncOptions:
    #- CreateNamespace=true