---
apiVersion: v1
kind: Namespace
metadata:
  name: swagger-demo
  labels:
    #argocd.argoproj.io/managed-by: openshift-gitops
    #argocd.argoproj.io/managed-by: ocp-gitops
  #finalizers:
  #- resources-finalizer.argocd.argoproj.io
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:  
  name: demo-apps
  #namespace: ocp-gitops
  namespace: openshift-gitops
  labels:
    appgrp: demo-app
    owner: gsb
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destinations:
    - namespace: swagger-demo      
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - 'https://gsbraman.github.io/stp/'
    - 'https://github.com/gsbraman/stp'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app3-swagger
  #namespace: ocp-gitops
  namespace: openshift-gitops
  labels:
    appgrp: demo-apps
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: demo-apps
  source:
    repoURL: https://github.com/gsbraman/stp
    path: src/swagger
    targetRevision: HEAD
    ## BELOW is to use the helm chart
    #repoURL: https://gsbraman.github.io/stp/
    #chart: swagger
    #targetRevision: 7.0.3  # chart version
    ## override default values in values.yaml
    #helm:
      #values: |        
        #containerLimitsCpu: "400m"
        #containerLimitsMemory: "300Mi"       
  destination:    
    server: https://kubernetes.default.svc
    namespace: swagger-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
...
