apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grpc-hog
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gsbraman.github.io/stp/
    targetRevision: 1.0.2
    chart: hogchart    
  destination:
    server: https://kubernetes.default.svc
    namespace: grpc
  syncPolicy:
    automated:
      selfHeal: true