apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:  
  name: app2-helm-repos
  namespace: ocp-gitops
  #namespace: openshift-gitops
  labels:
    appgrp: demo-app    
  #finalizers:
  #- resources-finalizer.argocd.argoproj.io
spec:
  destination:    
    server: https://kubernetes.default.svc
  project: default
  source:
    #directory:
      #recurse: true
    path: src/helm-repos
    repoURL: https://github.com/gsbraman/stp
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
