apiVersion: v2
appVersion: 1.0.0
description: gRPC-Multus Application
icon: https://cncf-branding.netlify.app/img/projects/grpc/horizontal/color/grpc-horizontal-color.png
name: grpc
type: application
version: 1.0.0
