# Default values for grpc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: grpc
namespace: default
app: grpc
owner: sbraman
vendor: stp
#imagePullPolicy: Always
#restartPolicy: Always
#containerName: 
#containerImage: 
#containerRequestsMemory: "100Mi"
#containerRequestsCpu: "200m"
#containerLimitsMemory: "200Mi"
#containerLimitsCpu: "300m"