apiVersion: metallb.io/v1alpha1
kind: AddressPool
metadata:
  namespace: metallb-system
  name: metallb-pool-1
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  protocol: layer2
  addresses:
  - 192.168.130.20-192.168.130.30