apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:  
  name: master-app
  namespace: ocp-gitops
  #namespace: openshift-gitops
  labels:
    appgrp: day2
    #argocd.argoproj.io/managed-by: ocp-gitops
  #finalizers:
  #- resources-finalizer.argocd.argoproj.io  
spec:
  destination:    
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: gitops/apps
    repoURL: https://github.com/gsbraman/stp
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
